### ISSUE TITLE
Doorkeeper 2 & Wine Bouncer

### ISSUE THREAD

**Issue by whatasunnyday** [antek-drzewiecki/wine_bouncer#10]
Hey Antek,

Thanks for all your hard work with wine bouncer. It's a great gem! 

I was planning to use it with Doorkeeper 2.0.1 and I noticed that I get this error from master

```
Bundler could not find compatible versions for gem "doorkeeper":
  In Gemfile:
    wine_bouncer (>= 0) ruby depends on
      doorkeeper (~> 1.4.0) ruby

    doorkeeper (2.0.1)
```

I see there's a doorkeeper 2 branch but it's only 1 commit higher than master. It looks the build is passing. Is it cool to use doorkeeper 2 and wine bouncer? Is there anything I should be watching out for?

**Comment by whatasunnyday** [comment]
It appears that doorkeeper 2.0.1 isn't working either :(.

```
λ →  bundle install
Fetching https://github.com/antek-drzewiecki/wine_bouncer.git
Fetching gem metadata from https://rubygems.org/.........
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "doorkeeper":
  In Gemfile:
    wine_bouncer (>= 0) ruby depends on
      doorkeeper (<= 2.0.0.alpha1, >= 1.4) ruby

    doorkeeper (2.0.1)
```

**Comment by whatasunnyday** [comment]
I was able to get the tests running and passing with minor changes. The only blocker was copying the method definition from https://github.com/doorkeeper-gem/doorkeeper/commit/e0ecef7b6a2e1a6ddc9f6ae774a05cfe71b2f075#diff-2dac7b5ba275c2921a0ad8385afea15bR209 since the rails_helper was relying on it. I just sent a PR. Please review and let me know if there's anything I can do to help.

**Comment by whatasunnyday** [comment]
Hello! I was only able to test the integration recently and ran into some problems. First, I got an initialized constant error inside of where I registered WineBouncer as middleware. Requiring wine_bouncer solved the problem. Now, I get the following stack trace when I try to protect a route:

```ruby
module V0
  module User
    class First < Grape::API
      desc 'Return the first User object'
      auth: { scopes: ['public'] }
      get :first do
        { user: ::User.first }
      end
    end
  end
end

```

```
=> Booting WEBrick
=> Rails 4.2.0 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/home/wasd/Programs/rails_projects/Swyp/app/api/user/first.rb:1:in `<top (required)>': User is not a module (TypeError)
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/wasd/Programs/rails_projects/Swyp/app/api/api.rb:5:in `<class:API>'
	from /home/wasd/Programs/rails_projects/Swyp/app/api/api.rb:1:in `<top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:456:in `load_file'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /home/wasd/Programs/rails_projects/Swyp/config/routes.rb:4:in `block in <top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
	from /home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
	from /home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
	from /home/wasd/Programs/rails_projects/Swyp/config/routes.rb:1:in `<top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /home/wasd/Programs/rails_projects/Swyp/config/environment.rb:5:in `<top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /home/wasd/Programs/rails_projects/Swyp/config.ru:3:in `block in <main>'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /home/wasd/Programs/rails_projects/Swyp/config.ru:in `new'
	from /home/wasd/Programs/rails_projects/Swyp/config.ru:in `<main>'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:61:in `app'
	from /home/wasd/.gem/ruby/2.2.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/server.rb:78:in `start'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/wasd/Programs/rails_projects/Swyp/bin/rails:8:in `require'
	from /home/wasd/Programs/rails_projects/Swyp/bin/rails:8:in `<top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/client/rails.rb:27:in `call'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/client/command.rb:7:in `call'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/client.rb:26:in `run'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/bin/spring:48:in `<top (required)>'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `load'
	from /home/wasd/.gem/ruby/2.2.0/gems/spring-1.2.0/lib/spring/binstub.rb:11:in `<top (required)>'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/wasd/.rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/wasd/Programs/rails_projects/Swyp/bin/spring:16:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by whatasunnyday** [comment]
I just realized I missed the comma at the end of desc. Looks like everything is working great. Thanks again for your hardwork! :+1:

**Comment by antek-drzewiecki** [comment]
Sorry that i didn't reply earlier. I was on a holiday. Good that you solved your issue. 
The Doorkeeper 2.0.1 support will be there any time soon.

**Comment by whatasunnyday** [comment]
Happy holidays! Thank you very much for your hard work.
