### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by whatasunnyday** [antek-drzewiecki/wine_bouncer#36]
Hey, trying out the new syntax. Any idea why this might be happening?

 ```ruby
desc 'Raises error'
oauth2 'public'
get '/raises-error' do
   # Code
end
```

I'm using wine_bouncer (0.3.1).

```
SyntaxError: /home/wasd/Programs/rails_projects/Swyp/app/api_engine/api.rb:48: syntax error, unexpected '\n', expecting =>
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
/home/wasd/Programs/rails_projects/Swyp/config/routes.rb:4:in `block (2 levels) in <top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:816:in `scope'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/mapper.rb:940:in `constraints'
/home/wasd/Programs/rails_projects/Swyp/config/routes.rb:2:in `block in <top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
/home/wasd/.gem/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
/home/wasd/Programs/rails_projects/Swyp/config/routes.rb:1:in `<top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `each'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:40:in `load_paths'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:16:in `reload!'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:26:in `block in updater'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `call'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/file_update_checker.rb:75:in `execute'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:27:in `updater'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/home/wasd/Programs/rails_projects/Swyp/config/environment.rb:5:in `<top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/Programs/rails_projects/Swyp/test/test_helper.rb:4:in `<top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/Programs/rails_projects/Swyp/test/api_engine/api_test.rb:1:in `<top (required)>'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/wasd/.gem/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `block (3 levels) in define'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `each'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:114:in `block (2 levels) in define'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:113:in `each'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:113:in `block in define'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/sub_test_task.rb:20:in `invoke_rake_task'
/home/wasd/.gem/ruby/2.2.0/gems/railties-4.2.0/lib/rails/test_unit/testing.rake:8:in `block in <top (required)>'
Tasks: TOP => test:run
(See full trace by running task with --trace)
Coverage report generated for MiniTest to /home/wasd/Programs/rails_projects/Swyp/coverage. 0 / 0 LOC (100.0%) covered.

```

**Comment by antek-drzewiecki** [comment]
Your syntax seems to be ok. Can you please tell me what grape version you are running?
It seems to be the description that is causing the error. 
Try removing the description to be sure. or replace it by `desc 'Raises error',{}` just for a quick test.

**Comment by antek-drzewiecki** [comment]
@whatasunnyday still got difficulties? I couldn't really reproduce it.

**Comment by whatasunnyday** [comment]
Sorry @antek-drzewiecki. I still have some difficulties but I'm fighting a major release for this week. I'll get back to this by the weekend if you don't mind.

**Comment by antek-drzewiecki** [comment]
No problem at all, take your time :)

**Comment by whatasunnyday** [comment]
@antek-drzewiecki Regenerating my Gemfile.lock solved the problem! I have no idea why :).
